### ISSUE TITLE
Inject preload polyfill?

### ISSUE THREAD

**Issue by rafaelrinaldi** [GoogleChromeLabs/preload-webpack-plugin#20]
As of today [only Chrome supports `preload`](http://caniuse.com/#search=preload). Would it make sense to provide an option where Webpack can inject a `preload` polyfill? Either by specifying a chunk or really just inlining in the HTML (which makes more sense I guess).

Happy to try a PR if that sounds reasonable.

**Comment by addyosmani** [comment]
Good question. I've been given commit access to what I believe is a pretty comprehensive preload polyfill over at https://github.com/aFarkas/link-preload, but have been unsure how much value polyfilling this feature vs. allowing browsers to handle prioritization themselves when it isn't around might be.

@yoavweiss I think you shared some concern about polyfilling preload at BlinkOn. Any thoughts on the polyfill work above? :)

**Comment by yoavweiss** [comment]
@addyosmani is there a test site where I can see that polyfill in action? I'd expect it to double download, especially in non-WebKit browsers. /cc @aFarkas

**Comment by addyosmani** [comment]
@yoavweiss I just deployed the test suite here: https://preload-polyfill-test.firebaseapp.com/link-preload/test/manual-test.html 

This appears to be avoiding duplicate requests in Firefox but I'm still double checking:

![screen shot 2017-03-05 at 9 56 02 pm](https://cloud.githubusercontent.com/assets/110953/23598326/9ff761a6-01ee-11e7-8f6d-e9f501f17a5a.jpg)

**Comment by yoavweiss** [comment]
@addyosmani looks like it does in WebKit, when the resource is actually used: http://test.weissyoav.com/tests/preload_polyfill/manual-test.html

**Comment by aFarkas** [comment]
@yoavweiss 
I just tested it. With normal cache headers it shows twice in network but second is cached. In case you inline the script it is only visible once.

Image about twice, but cached loading.
<img width="926" alt="polyfill-chrome" src="https://cloud.githubusercontent.com/assets/188254/23635028/ab8fc33e-02cd-11e7-8459-e01948657191.png">

Image showing just one request (https://afarkas.github.io/link-preload/test/inline-test.html):
<img width="741" alt="polyfill-inline-chrome" src="https://cloud.githubusercontent.com/assets/188254/23635053/c67541ba-02cd-11e7-9e43-d1906806eb42.png">

The result in Safari are the same. Is this okish for you?

About polyfilling this feature:
Does it make sense? It depends. The main problem is that the "preload" aspect can't really be polyfilled unless you require some embed hacks, that might degrade performance for browsers, that already support this feature.

You need to inline the JS before any other external resource (including crucial stylesheet) to have similar preload aspects as the native implementation.

I personally wouldn't use the polyfill myself. But what I actually use is the technique to include 1-15kb of JS inlined in the head before any other external resource to conditionally preload assets and make important API calls. (A really underrated technique.)

**Comment by yoavweiss** [comment]
Yeah, if your resource is cacheable than the second load would happen from cache. I still don't think polyfilling `preload` (or using `prefetch` as a "fallback" despite its different semantics) is a good idea. `preload` as a performance enhancement can simply fallback to not having that performance enhancement in non-supporting browsers.

**Comment by jeffposnick** [comment]
Given the conclusion in https://github.com/GoogleChromeLabs/preload-webpack-plugin/issues/20#issuecomment-284632631, I'm closing this request.
