### ISSUE TITLE
Duplicate outputs when using with multiple instances of HtmlWebpackPlugin 

### ISSUE THREAD

**Issue by pplewa** [GoogleChromeLabs/preload-webpack-plugin#27]
```
new HtmlWebpackPlugin({ filename: '../file-1.html' }),
new HtmlWebpackPlugin({ filename: '../file-2.html' }),
new PreloadWebpackPlugin({ rel: 'prefetch', as: 'script' })
```
produces `file-1.html` with
```
<link rel="prefetch" src="chunk.0.js">
<link rel="prefetch" src="chunk.1.js">
</head>
```
and `file-2.html` with
```
<link rel="prefetch" src="chunk.0.js">
<link rel="prefetch" src="chunk.1.js">
<link rel="prefetch" src="chunk.0.js">
<link rel="prefetch" src="chunk.1.js">
</head>
```
and so on

**Comment by TheLarkInn** [comment]
I'm wondering if this is because it creates multiple child compilations.

**Comment by addyosmani** [comment]
@TheLarkInn I think you might be right. Is there a recommended workaround pattern you might suggest for better handling child compilations to avoid running into this issue?

**Comment by mike-north** [comment]
I'm seeing something very similar, even without multiple `HtmlWebpackPlugin` instances (in this case, it may be hot reloading that's causing this). Is it possible that with each pass, new link tags are added but old ones are not cleaned up?

A new link tag is added each time I save a file (not for each unique hash -- there are duplicates below) allow the webpack build to complete, and webpack-dev-server to trigger a hot reload.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <title>Preload all the things!</title>
    <link rel="preload" href="app-93e6af0808c654ad310c.js" as="script">
    <link rel="preload" href="app-371fc9b6d6d96cf9db90.js" as="script">
    <link rel="preload" href="app-c58fe4ec0cacebc4e33b.js" as="script">
    <link rel="preload" href="app-ecdb538ae72b77f444dd.js" as="script">
    <link rel="preload" href="app-30a12184754be02a9379.js" as="script">
    <link rel="preload" href="app-e80f5516c5eec6cb8fbf.js" as="script">
    <link rel="preload" href="app-30a12184754be02a9379.js" as="script">
    <link rel="preload" href="app-298e54e9cf594975e405.js" as="script">
    <link rel="preload" href="app-0dabec58b395f42fa4f0.js" as="script">
    <link rel="preload" href="app-298e54e9cf594975e405.js" as="script">
    <link rel="preload" href="app-0dabec58b395f42fa4f0.js" as="script">
    <link rel="preload" href="app-298e54e9cf594975e405.js" as="script">
    <link href="app-d800882673463ba49767a5235a256795.css" rel="stylesheet">
  </head>
  <body>
    <div id="root"></div>
    <script type="text/javascript" src="app-298e54e9cf594975e405.js"></script>
  </body>
</html>
```

<img width="511" alt="screen shot 2017-07-11 at 5 46 09 pm" src="https://user-images.githubusercontent.com/558005/28077056-de62154a-6660-11e7-8d87-76b6528268d7.png">

```
webpack: 3.1.0
preload-webpack-plugin: 1.2.2
html-webpack-plugin: 2.29.0
```

**Comment by nikhileshsomani** [comment]
Even I am facing the same thing. Any solution for this?

**Comment by addyosmani** [comment]
@mike-north 

> I'm seeing something very similar, even without multiple HtmlWebpackPlugin instances (in this case, it may be hot reloading that's causing this). Is it possible that with each pass, new link tags are added but old ones are not cleaned up?

Is it possible to confirm if you're seeing this without hot reloading too? Our tests don't currently cover the plugin being used in a HMR setup so I wouldn't be surprised if this was happening during dev. It _shouldn't_ be happening on a final production build however. If it is that's definitely a bug.

**Comment by TheLarkInn** [comment]
@addyosmani Agreed.

@pplewa you wouldn't happen to have a reproducible repository of this setup anywhere that I could clone would you? This would allow me to better diagnose what may be causing the problem. I'll try and use the information I have to see if it yields any results.

**Comment by pplewa** [comment]
yup created one: https://github.com/pplewa/preload-webpack-duplicates

**Comment by TheLarkInn** [comment]
Thank you! I was able to catch an example myself as well. So I'm seeing the following: 

**webpack.config.js**
```js
const path = require("path");
const webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const PreloadWebpackPlugin = require("preload-webpack-plugin");

module.exports = {
    entry: "./src/index.js",
    output: {
        path: path.join(__dirname, "dist"),
        filename: "bundle.js"
    },
    plugins: [
        new HtmlWebpackPlugin({ filename: 'file-1.html' }),
        new HtmlWebpackPlugin({ filename: 'file-2.html' }),
        new PreloadWebpackPlugin({ rel: 'prefetch', as: 'script' }),
        function apply() {
            this.plugin("compilation", compilation => {
                compilation.plugin("html-webpack-plugin-alter-asset-tags", (compilationObject, cb) => {
                    debugger;
                    cb(null, compilationObject);
                });
                compilation.plugin("html-webpack-plugin-after-html-processing", (compilationObject, cb) => {
                    debugger;
                    cb(null, compilationObject);
                })
            })
        }
    ]
};
```

I believe that this could potentially not be the fault of this plugin specifically but perhaps an agressively cached or shared reference of the same "before template is applied, default html file". One suggestion I could make is instead trying the "html-webpack-plugin-alter-asset-tags" hook. 

With this you can specify where and what tags and respective properties inside a data object and it should be added into the html file w/o duplication. I was leveraging this @ mutualofomaha and using around 50 instances of html-webpack-plugin on a single configuration without issues. 

```
compilation.plugin("html-webpack-plugin-alter-asset-tags", (compilationObject, cb) => {
    debugger;
    cb(null, compilationObject);
});
```

This would be a good place to start at least.

**Comment by knpwrs** [comment]
I'm seeing this issue with HMR and one plugin instance.

![image](https://user-images.githubusercontent.com/174864/29038439-ab31652a-7b75-11e7-9551-6ac3d94bb2e7.png)

My configuration is as such:

```js
// ...
plugins: [
  new HtmlPlugin({
    title: 'PCO GraphQL Demo',
  }),
  new PreloadPlugin({
    fileBlacklist: [/\.hot-update\.js$/],
  }),
],
// ...
```
