### ISSUE TITLE
Whitelisting chunks

### ISSUE THREAD

**Issue by wanecek** [GoogleChromeLabs/preload-webpack-plugin#38]
It would be useful if preload-webpack-plugin supported an option to filter chunks using a whitelist as a complement to the current `fileBlacklist` option.

My suggestion would be to allow the `include` option to contain a Regular Expressions in addition to strings.

I'm happy to submit a PR, if this is something that others would also find useful 😊 

---

Related to #6

**Comment by frlinw** [comment]
https://github.com/GoogleChromeLabs/preload-webpack-plugin/pull/36 introduce `fileWhitelist` but still waiting for merge
