### ISSUE TITLE
Multiple html plugins

### ISSUE THREAD

**Issue by furstenheim** [GoogleChromeLabs/preload-webpack-plugin#48]
Hi,
I have the following use case. In a webpack config I'm creating several html files as in [this question](https://stackoverflow.com/questions/39798095/multiple-html-files-using-webpack). I can't find any way in the documentation to treat that case with preload webpack plugin. That is:

    plugins: [
      new HtmlWebpackPlugin({
        filename: 'index.html',
        template: 'src/index.html',
        chunks: ['main']
      }),
      new HtmlWebpackPlugin({
        filename: 'example.html',
        template: 'src/example.html',
        chunks: ['exampleEntry']
      }),
      // I want this to affect only index.html
      new PreloadWebpackPlugin()     
    ]

Is it possible to do it with this plugin? In the README there are only examples on how to filter the chunks, but not the destination.

Thanks

**Comment by jeffposnick** [comment]
Are you using the new `2.1.1` release? It includes changes that affect the multiple HtmlWebpackPlugin use case: https://github.com/GoogleChromeLabs/preload-webpack-plugin/pull/37/files

Before debugging further, I wanted to clarify that.

**Comment by furstenheim** [comment]
I wasn't aware it existed. In any case in the pr that you mention there isn't yet any example with multiple files, right? For example, in [demo webpack config](https://github.com/toxic-johann/preload-webpack-plugin/blob/5d8a9ed72c963e05e05a1a76ca48f15360fdbb6b/demo/webpack.config.js#L85) there are indeed two html plugins but there is no configuration in the preload plugin of what html it should affect.

    new webpack.LoaderOptionsPlugin({
      minimize: true,
      debug: false
    })

**Comment by toxic-johann** [comment]
@jeffposnick Hmmm. Actually we have not provide an option to choose which entry should be handled. But we have [fileBlackList](https://github.com/GoogleChromeLabs/preload-webpack-plugin#filtering-chunks), which can do this job, but seems weird.

Maybe we can introduce a new option. I think I can do this.

**Comment by huanggm** [comment]
@toxic-johann Does this question been resolved?

**Comment by jeffposnick** [comment]
I've merged #54, which should fix this in a backwards-compatible fashion. Thanks, @toxic-johann!

I think we could benefit from rethinking what the ideal interface would be in an upcoming major version release, where there is some flexibility in breaking the existing interface. I'll open an issue in the near-future with a proposal (once I've had some time to think about it as well), and I'd love input there.

CC: @addyosmani
