### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChromeLabs/preload-webpack-plugin#52]
Webpack 4 (which I hear is shipping in Feb. 2018) will introduce [changes to the plugin system](https://medium.com/webpack/the-new-plugin-system-week-22-23-c24e3b22e95), and there might be changes required for this plugin to be compatible.

I don't specifically know what might need to change, but I'm opening this as a placeholder to investigate further, and an opportunity to folks from the community who have been involved in migrating other plugins to contribute.

**Comment by beheh** [comment]
I see at least two things that need to happen:
- Update compiler/compliation.plugin to the new Tapable api (using hook and hookAsync respectively)  
This'll need a conditional branch if we still want to support webpack <4
- Change `chunks.parents` to use `ChunkGroup.getParents()`, according to a fatal error from webpack   I'm not sure where that'll come from, and it'll need to passed into `doesChunkBelongToHTML`.
