### ISSUE TITLE
Adding 'preconnect'

### ISSUE THREAD

**Issue by aroramayur** [GoogleChromeLabs/preload-webpack-plugin#58]
Can we use this plugin to add a 'preconnect' resource hint ? If yes, can someone share an example

**Comment by jeffposnick** [comment]
This plugin is focused on automating `<link>` creation associated with the output of a webpack build.

`<link rel='preconnect' ...>` is used with a specific origin URL, not with a asset/subresource URL. Your best bet is to add in `<link rel='preconnect'>` elements with hardcoded origin URLs in your `html-webpack-plugin` template.
