### ISSUE TITLE
[v3] fileWhitelist removed

### ISSUE THREAD

**Issue by frlinw** [GoogleChromeLabs/preload-webpack-plugin#63]
No more `fileWhitelist` filtering in v3 alpha. is it intended ?
https://github.com/GoogleChromeLabs/preload-webpack-plugin/blob/v3/src/index.js#L63

**Comment by frlinw** [comment]
One more little thing FYI, with html-webpack-plugin 3.2.0 and webpack 4.5

```npm WARN preload-webpack-plugin@3.0.0-alpha.1 requires a peer of html-webpack-plugin@^2.26.0 but none is installed. You must install peer dependencies
yourself.
npm WARN preload-webpack-plugin@3.0.0-alpha.1 requires a peer of webpack@^3.2.0 but none is installed. You must install peer dependencies yourself.```

**Comment by jeffposnick** [comment]
Thanks! Omitting `fileWhitelist` was an oversight, and I've updated the `devDependencies` to use `>=`.

Can you give `preload-webpack-plugin@3.0.0-alpha.3` a try and confirm that things work as expected for you?

**Comment by frlinw** [comment]
Thanks, It works 👍

**Comment by michaelolo24** [comment]
it looks like it was removed again in beta.3 (unless I missed something)
