### ISSUE TITLE
media tag for images [enhancement]

### ISSUE THREAD

**Issue by maulpets** [GoogleChromeLabs/preload-webpack-plugin#69]
Is it possible to include a media tag for certain preloaded assets.  Specifically i want to include a preload link for my banner images.  The desired output would be something like this below.   

	
	<link rel="preload" as="image" href="images/landing-page-banner_mobile.jpg" media="(max-width: 600px)">
	<link rel="preload" as="image" href="images/landing-page-banner_s.jpg" media="(max-width: 960px)">
	<link rel="preload" as="image" href="images/landing-page-banner_m.jpg" media="(max-width: 1440px)">
	<link rel="preload" as="image" href="images/landing-page-banner_l.jpg" media="(min-width: 1441px)">

**Comment by ansf** [comment]
I don't understand how #99 solves this issue. I think we need some kind of Map where we can specify different media-attributes for different file patterns.

Right now it looks like we have the same media-attribute for all <link>s. Or am I missing something?
