### ISSUE TITLE
No preload links inserted for fonts?

### ISSUE THREAD

**Issue by DavidBanksNZ** [GoogleChromeLabs/preload-webpack-plugin#83]
I'm working on a PWA built using preact cli and I would like to have my font files preloaded but having tried fiddling with my config for hours, it never works.

In my SCSS I have some font declarations

```
@font-face {
	font-family: 'Inter UI';
	font-display: fallback;
	font-style:  normal;
	font-weight: 400;
	src: url("../assets/fonts/Inter-UI-Regular.woff2") format("woff2"),
	url("../assets/fonts/Inter-UI-Regular.woff") format("woff");
}

@font-face {
	font-family: 'Inter UI';
	font-display: fallback;
	font-style:  normal;
	font-weight: 600;
	src: url("../assets/fonts/Inter-UI-SemiBold.woff2") format("woff2"),
	url("../assets/fonts/Inter-UI-SemiBold.woff") format("woff");
}
```

And I've tried the `allAssets` and `fileWhiteList` settings as described in the README, but there is never any preload links inserted in the HTML. 

I have seen that this feature was supported in 2.3.0 which is the version I'm using, so I'm confused why it's not working...

**Comment by DavidBanksNZ** [comment]
Sorry had a misunderstanding. The fonts were getting included in the build only, because url-loader inlining them when running in dev mode.

Also in the README, it should probably have in the example to use `include: "allAssets"` and `filterWhitelist: []` together. It took me a little while to realise that, the README example shows filterWhitelist on its own

**Comment by jeffposnick** [comment]
Apologies—the README and API surface is getting some updates for the `v3` release, as well: https://github.com/GoogleChromeLabs/preload-webpack-plugin/releases/tag/v3.0.0-beta.1
